/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.vmware.sbp.kubereport.controller.spring.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import jp.vmware.sbp.kubereport.controller.spring.models.V1alpha1SpreadsheetStatusAggregated;
import jp.vmware.sbp.kubereport.controller.spring.models.V1alpha1SpreadsheetStatusFormatted;

/**
 * SpreadsheetStatus defines the observed state of Spreadsheet
 */
@ApiModel(description = "SpreadsheetStatus defines the observed state of Spreadsheet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-06T03:12:04.488Z[Etc/UTC]")
public class V1alpha1SpreadsheetStatus {
  public static final String SERIALIZED_NAME_AGGREGATED = "aggregated";
  @SerializedName(SERIALIZED_NAME_AGGREGATED)
  private V1alpha1SpreadsheetStatusAggregated aggregated;

  public static final String SERIALIZED_NAME_FORMATTED = "formatted";
  @SerializedName(SERIALIZED_NAME_FORMATTED)
  private V1alpha1SpreadsheetStatusFormatted formatted;

  public static final String SERIALIZED_NAME_FRIENDLY_DESCRIPTION = "friendlyDescription";
  @SerializedName(SERIALIZED_NAME_FRIENDLY_DESCRIPTION)
  private String friendlyDescription;


  public V1alpha1SpreadsheetStatus aggregated(V1alpha1SpreadsheetStatusAggregated aggregated) {
    
    this.aggregated = aggregated;
    return this;
  }

   /**
   * Get aggregated
   * @return aggregated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1SpreadsheetStatusAggregated getAggregated() {
    return aggregated;
  }


  public void setAggregated(V1alpha1SpreadsheetStatusAggregated aggregated) {
    this.aggregated = aggregated;
  }


  public V1alpha1SpreadsheetStatus formatted(V1alpha1SpreadsheetStatusFormatted formatted) {
    
    this.formatted = formatted;
    return this;
  }

   /**
   * Get formatted
   * @return formatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1SpreadsheetStatusFormatted getFormatted() {
    return formatted;
  }


  public void setFormatted(V1alpha1SpreadsheetStatusFormatted formatted) {
    this.formatted = formatted;
  }


  public V1alpha1SpreadsheetStatus friendlyDescription(String friendlyDescription) {
    
    this.friendlyDescription = friendlyDescription;
    return this;
  }

   /**
   * FriendlyDescription is a string indicating the status
   * @return friendlyDescription
  **/
  @ApiModelProperty(required = true, value = "FriendlyDescription is a string indicating the status")

  public String getFriendlyDescription() {
    return friendlyDescription;
  }


  public void setFriendlyDescription(String friendlyDescription) {
    this.friendlyDescription = friendlyDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SpreadsheetStatus v1alpha1SpreadsheetStatus = (V1alpha1SpreadsheetStatus) o;
    return Objects.equals(this.aggregated, v1alpha1SpreadsheetStatus.aggregated) &&
        Objects.equals(this.formatted, v1alpha1SpreadsheetStatus.formatted) &&
        Objects.equals(this.friendlyDescription, v1alpha1SpreadsheetStatus.friendlyDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregated, formatted, friendlyDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SpreadsheetStatus {\n");
    sb.append("    aggregated: ").append(toIndentedString(aggregated)).append("\n");
    sb.append("    formatted: ").append(toIndentedString(formatted)).append("\n");
    sb.append("    friendlyDescription: ").append(toIndentedString(friendlyDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

