/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.vmware.sbp.kubereport.controller.spring.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SpreadsheetSpec defines the desired state of Spreadsheet
 */
@ApiModel(description = "SpreadsheetSpec defines the desired state of Spreadsheet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-06T03:12:04.488Z[Etc/UTC]")
public class V1alpha1SpreadsheetSpec {
  public static final String SERIALIZED_NAME_KUBE_AGGREGATOR_U_R_L = "kubeAggregatorURL";
  @SerializedName(SERIALIZED_NAME_KUBE_AGGREGATOR_U_R_L)
  private String kubeAggregatorURL;

  public static final String SERIALIZED_NAME_KUBE_FORMATTER_U_R_L = "kubeFormatterURL";
  @SerializedName(SERIALIZED_NAME_KUBE_FORMATTER_U_R_L)
  private String kubeFormatterURL;

  public static final String SERIALIZED_NAME_SCRAPE_RESOURCES = "scrapeResources";
  @SerializedName(SERIALIZED_NAME_SCRAPE_RESOURCES)
  private List<String> scrapeResources = null;

  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private Boolean summary;

  public static final String SERIALIZED_NAME_TARGET_NAMESPACES = "targetNamespaces";
  @SerializedName(SERIALIZED_NAME_TARGET_NAMESPACES)
  private List<String> targetNamespaces = null;

  public static final String SERIALIZED_NAME_VSPHERE = "vsphere";
  @SerializedName(SERIALIZED_NAME_VSPHERE)
  private Boolean vsphere;


  public V1alpha1SpreadsheetSpec kubeAggregatorURL(String kubeAggregatorURL) {
    
    this.kubeAggregatorURL = kubeAggregatorURL;
    return this;
  }

   /**
   * KubeAggregatorURL is a string to specify the aggregator URL.
   * @return kubeAggregatorURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KubeAggregatorURL is a string to specify the aggregator URL.")

  public String getKubeAggregatorURL() {
    return kubeAggregatorURL;
  }


  public void setKubeAggregatorURL(String kubeAggregatorURL) {
    this.kubeAggregatorURL = kubeAggregatorURL;
  }


  public V1alpha1SpreadsheetSpec kubeFormatterURL(String kubeFormatterURL) {
    
    this.kubeFormatterURL = kubeFormatterURL;
    return this;
  }

   /**
   * KubeFormatterURL is a string to specify the formatter URL.
   * @return kubeFormatterURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KubeFormatterURL is a string to specify the formatter URL.")

  public String getKubeFormatterURL() {
    return kubeFormatterURL;
  }


  public void setKubeFormatterURL(String kubeFormatterURL) {
    this.kubeFormatterURL = kubeFormatterURL;
  }


  public V1alpha1SpreadsheetSpec scrapeResources(List<String> scrapeResources) {
    
    this.scrapeResources = scrapeResources;
    return this;
  }

  public V1alpha1SpreadsheetSpec addScrapeResourcesItem(String scrapeResourcesItem) {
    if (this.scrapeResources == null) {
      this.scrapeResources = new ArrayList<>();
    }
    this.scrapeResources.add(scrapeResourcesItem);
    return this;
  }

   /**
   * ScrapeResources is an list of resources to scrape of Spreadsheet.
   * @return scrapeResources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ScrapeResources is an list of resources to scrape of Spreadsheet.")

  public List<String> getScrapeResources() {
    return scrapeResources;
  }


  public void setScrapeResources(List<String> scrapeResources) {
    this.scrapeResources = scrapeResources;
  }


  public V1alpha1SpreadsheetSpec summary(Boolean summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Summary is a boolean to add whether or not summary page in Spreadsheet.
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Summary is a boolean to add whether or not summary page in Spreadsheet.")

  public Boolean getSummary() {
    return summary;
  }


  public void setSummary(Boolean summary) {
    this.summary = summary;
  }


  public V1alpha1SpreadsheetSpec targetNamespaces(List<String> targetNamespaces) {
    
    this.targetNamespaces = targetNamespaces;
    return this;
  }

  public V1alpha1SpreadsheetSpec addTargetNamespacesItem(String targetNamespacesItem) {
    if (this.targetNamespaces == null) {
      this.targetNamespaces = new ArrayList<>();
    }
    this.targetNamespaces.add(targetNamespacesItem);
    return this;
  }

   /**
   * TargetNamespaces is an list of namespaces to scrape of Spreadsheet.
   * @return targetNamespaces
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TargetNamespaces is an list of namespaces to scrape of Spreadsheet.")

  public List<String> getTargetNamespaces() {
    return targetNamespaces;
  }


  public void setTargetNamespaces(List<String> targetNamespaces) {
    this.targetNamespaces = targetNamespaces;
  }


  public V1alpha1SpreadsheetSpec vsphere(Boolean vsphere) {
    
    this.vsphere = vsphere;
    return this;
  }

   /**
   * VSphere is a boolean to add whether or not vsphere page in Spreadsheet.
   * @return vsphere
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VSphere is a boolean to add whether or not vsphere page in Spreadsheet.")

  public Boolean getVsphere() {
    return vsphere;
  }


  public void setVsphere(Boolean vsphere) {
    this.vsphere = vsphere;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SpreadsheetSpec v1alpha1SpreadsheetSpec = (V1alpha1SpreadsheetSpec) o;
    return Objects.equals(this.kubeAggregatorURL, v1alpha1SpreadsheetSpec.kubeAggregatorURL) &&
        Objects.equals(this.kubeFormatterURL, v1alpha1SpreadsheetSpec.kubeFormatterURL) &&
        Objects.equals(this.scrapeResources, v1alpha1SpreadsheetSpec.scrapeResources) &&
        Objects.equals(this.summary, v1alpha1SpreadsheetSpec.summary) &&
        Objects.equals(this.targetNamespaces, v1alpha1SpreadsheetSpec.targetNamespaces) &&
        Objects.equals(this.vsphere, v1alpha1SpreadsheetSpec.vsphere);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kubeAggregatorURL, kubeFormatterURL, scrapeResources, summary, targetNamespaces, vsphere);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SpreadsheetSpec {\n");
    sb.append("    kubeAggregatorURL: ").append(toIndentedString(kubeAggregatorURL)).append("\n");
    sb.append("    kubeFormatterURL: ").append(toIndentedString(kubeFormatterURL)).append("\n");
    sb.append("    scrapeResources: ").append(toIndentedString(scrapeResources)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    targetNamespaces: ").append(toIndentedString(targetNamespaces)).append("\n");
    sb.append("    vsphere: ").append(toIndentedString(vsphere)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

