apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubereport-controller
  namespace: system
spec:
  selector:
    matchLabels:
      app: kubereport-controller
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kubereport-controller
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubereport-controller
      containers:
        - image: ghcr.io/tanzu-japan/kubereport-controller-spring::0.0.1-snapshot
          name: kubereport-controller
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 20m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
